export const ADD_TO_CART = "ADD-TO-CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADJUST_QTY = "ADJUST_QTY"
export const LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM";
export const SELL_ITEM = "SELL_ITEM";
export const ADD_TO_FAVOURITE = "ADD_TO_FAVOURITE";
export const REMOVE_FROM_FAVOURITE = "REMOVE_FROM_FAVOURITE";
export const USER_LOGIN = "USER_LOGIN";